insert into IngredientUnits (Title) values (N'پیمانه')
insert into IngredientUnits (Title) values (N'عدد')
insert into IngredientUnits (Title) values (N'سيخ')
insert into IngredientUnits (Title) values (N'قرص')
insert into IngredientUnits (Title) values (N'قطعه')
insert into IngredientUnits (Title) values (N'کیسه')
insert into IngredientUnits (Title) values (N'ليتر')
insert into IngredientUnits (Title) values (N'کیلو')
insert into IngredientUnits (Title) values (N'گرم')
insert into IngredientUnits (Title) values (N'سی سی')
insert into IngredientUnits (Title) values (N'حب')
insert into IngredientUnits (Title) values (N'دانه')
insert into IngredientUnits (Title) values (N'قاشق غذاخوری')
insert into IngredientUnits (Title) values (N'قاشق چای خوری')
