insert into RecipeCategories (Title) values (N'پیش غذا')
insert into RecipeCategories (Title) values (N'دسر')
insert into RecipeCategories (Title) values (N'سالاد')
insert into RecipeCategories (Title) values (N'کیک و شیرینی')
insert into RecipeCategories (Title) values (N'کباب')
insert into RecipeCategories (Title) values (N'خورشت')
insert into RecipeCategories (Title) values (N'نوشیدنی')
insert into RecipeCategories (Title) values (N'آش')
insert into RecipeCategories (Title) values (N'سنتی')
insert into RecipeCategories (Title) values (N'پلو')
